### ISSUE TITLE
ReplaceObjectEl sample does not work (no CKEditor)

### ISSUE THREAD

**Issue by AnnaTomanek** [ckeditor/ckeditor-java-webapp#6]
No CKEditor instance shows, devtools return:

replaceObjectEl.sample:77:
`Uncaught ReferenceError: CKEDITOR is not defined`

**Comment by jswiderski** [comment]
Fixed with 64e3bc1

It turned out that code returning CKEditor JavaScript was missing a call to method createHTML which adds ckeditor.js script reference.
